language: node_js
node_js: stable
install:
    - npm install
script:
    - hexo clean
    - hexo g
after_script:
    - cd ./public
    - git init
    - git config user.name "gXuanN"
    - git config user.email "tlfggx@gmail.com"
    - git add .
    - git commit -m "Travis CI Auto Builder"
    - git push --force --quiet "https://${Travis_token}@${GH_REF}" master:master
branches:
    only:
        - source
env:
    global:
        - GH_REF: github.com/guangxuan126/guangxuan126.github.io.git